#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright © 2003 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2003-06.

"""\
MIDI tools for Python - Simple player.
"""

import sys
from Midi import main
main.main(*sys.argv[1:])
